rule mach_alles:
    input: expand("build/{plotname}.pdf", plotname = ["justage_10", "justage_15"]),
    output: "main.pdf",
    shell: "lualatex main.tex"

rule mach_plot_justage:
    output:"build/{plotname}.pdf",
    shell: "python skript/{plotname}.py"

rule mach_plot_kalibration:
    output:"build/kalibration.pdf",
    shell: "python skript/kalibration.py"