(TeX-add-style-hook
 "4_analysis"
 (lambda ()
   (LaTeX-add-labels
    "fig:spectrumeu"
    "fig:background"
    "fig:eubackground"
    "eqn:linear"
    "tab:calibrationvalues"
    "eqn:fullenergy"
    "eqn:solidangle"
    "subsubsec:activity"
    "eqn:activation"
    "subsubsec:solidangle"
    "eqn:params"
    "subsubsec:determinationfep"
    "eqn:fedpfit_function"
    "fig:efit"
    "fig:csspectrum"
    "fig:csfit"
    "eqn:fitplus"
    "tab:csfitparams"
    "fig:csfwhm"
    "eqn:egamma"
    "eqn:emax"
    "fig:csshort"
    "fig:comptonfit"
    "eqn:comptonfit"))
 :latex)

